---
# Global variables for this TTN organization

# Pick a value from /usr/share/zoneinfo/REGION/ZONE, i.e. US/Eastern
timezone: "US/Eastern"
# Pick one of US (915) EU (868) AU (915)
region: US
# Whom to contact about issues with this gateway
contact_email: jch@honig.net
# Pick servers appropriate for the installed region
ntp_servers:
  - 0.north-america.pool.ntp.org
  - 1.north-america.pool.ntp.org
  - 2.north-america.pool.ntp.org
