#!/bin/sh

PROGNAME=$(basename $0)
LOGFILE=/var/log/lora-pkt-fwd.log
COOKIE=/var/run/${PROGNAME}

log() {
    logger -t ${PROGNAME} ${*}
}

fail() {
    echo "${*}"
    log "${*}"

    if [ -f ${COOKIE} ]; then
	rm -f ${COOKIE}
	exit 1
    fi

    touch ${COOKIE}

    exit 0
}

log Checking ${LOGFILE}

test -f ${LOGFILE} || fail "${LOGFILE} does not exist"

test -z "$(find /var/log/lora-pkt-fwd.log -mmin +10)" || fail "${LOGFILE} not being updated"

tail -2 ${LOGFILE} | grep -q -E "^INFO: Exiting packet forwarder program" && fail "Last message was quit"

tail -10 ${LOGFILE} | grep -q -E "^ERROR: \[main\] failed to start the concentrator" && fail "Packet fowarder failed to start"

tail -20 ${LOGFILE} | grep -q -E "(PULL_ACK received in)|(INFO: \[TTN\] send status success for)" || fail "No downlink messages"

rm -f ${COOKIE}

exit 0



