#!/bin/sh
#
#Start conduit_leds as a service

### BEGIN INIT INFO
# Provides:          conduit_leds
# Required-Start:    $local_fs $network $syslog $dbus
# Required-Stop:     $local_fs $network $syslog $dbus
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Display connection status in Conduit LEDs
### END INIT INFO

PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
NAME=conduit_leds
DAEMON=/usr/local/sbin/conduit_leds
PIDFILE=/var/run/${NAME}.pid
DAEMON_ARGS=

# source function library
. /etc/init.d/functions

if [ -r /etc/default/${NAME} ]; then
        . /etc/default/${NAME}
fi

[ -x ${DAEMON} ] || exit 0

is_running() {
    pgrep -F ${PIDFILE} > /dev/null 2>&1
}

start() {
    start-stop-daemon --start --quiet -p ${PIDFILE} --exec ${DAEMON} -- ${DAEMON_ARGS}
}

stop() {
    start-stop-daemon --stop --quiet --p ${PIDFILE}
}

case "$1" in
    start)
	if is_running; then
	    echo "${NAME} is already running: $(pgrep -F ${PIDFILE} -a)" >&2
	    exit 1
	fi
	echo "Starting ${NAME}" >&2
	start
	;;
    stop)
	if is_running; then
	    echo "Stopping ${NAME}" >&2
	    stop
	else
	    echo "${NAME} is not running" >&2
	fi
	;;
    restart|reload)
	if is_running; then
	    echo "Stopping ${NAME}" >&2
	    stop
	else
	    echo "${NAME} is not running" >&2
	fi

	# Wait for it to stop
	tries=10
	while is_running; do
	    if [ "${tries}" -eq 0 ]; then
		echo "${NAME} failed to stop" >&2
		exit 1
	    fi
	    tries=$((tries - 1))
	    sleep 1
	done

	echo "Starting ${NAME}" >&2
	start
	;;
    status)
	if is_running; then
	   echo "${NAME} is running with PID $(pgrep -F ${PIDFILE} -a)" >&2
	else
	    echo "${NAME} is not running" >&2
	    exit 1
	fi
	;;
    *)
	echo "Usage: $0 {start|stop|status|restart}" >&2
	exit 2
	;;
esac

exit 0
#=========================================
