#!/bin/sh

# Restart services when we get an address

[ $METHOD = "dhcp" ] && exit 0

logger -s -t $(basename ${0}) -p daemon.info "$METHOD interface $IFACE is up, restarting services"
test -x /etc/init.d/ttn-pkt-forwarder && /etc/init.d/ttn-pkt-forwarder restart
test -x /etc/init.d/lora-basic-station && /etc/init.d/lora-basic-station restart
test -x /etc/init.d/ssh_tunnel && /etc/init.d/ssh_tunnel restart

exit 0
