#!/bin/sh
#
#Start monitor_modem as a service

### BEGIN INIT INFO
# Provides:          monitor_modem
# Required-Start:    $local_fs $network $syslog $dbus
# Required-Stop:     $local_fs $network $syslog $dbus
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Display connection status in Conduit LEDs
### END INIT INFO

PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
NAME=monitor_modem
DAEMON=/usr/local/sbin/monitor_modem
PIDFILE=/var/run/${NAME}.pid
DAEMON_ARGS=

# source function library
. /etc/init.d/functions

if [ -r /etc/default/${NAME} ]; then
        . /etc/default/${NAME}
fi

[ -x ${DAEMON} ] || exit 0

is_running() {
    pgrep -F ${PIDFILE} > /dev/null 2>&1
}

start() {
    start-stop-daemon --start --quiet -p ${PIDFILE} --exec ${DAEMON} -- ${DAEMON_ARGS}
}

stop() {
    start-stop-daemon --stop --quiet --p ${PIDFILE}
}

case "$1" in
    start)
	is_running || start
	;;
    stop)
	stop
	;;
    restart|reload)
	stop
	start
	;;
    status)
	if is_running; then
	   echo "${NAME} is running with PID $(cat ${PIDFILE})" >&2
	else
	    echo "${NAME} is not running" >&2
	    exit 1
	fi
	;;
    *)
	echo "Usage: $0 {start|stop|status|restart}" >&2
	exit 2
	;;
esac

exit 0
#=========================================
