#!/bin/sh

# Restart services when we get an address

[ -z "$1" ] && echo "Error: should be called from udhcpc" && exit 1

case "$1" in
    deconfig)
        ;;

    bound)
	echo "$0: New IP address $ip on $interface, restarting services"
	test -x /etc/init.d/ttn-pkg-forwarder && /etc/init.d/ttn-pkt-forwarder restart
	test -x /etc/init.d/ssh_tunnel && /etc/init.d/ssh_tunnel restart
	;;

    renew)
	;;

    nak)
	;;
    
esac

exit 0
