#!/bin/bash

if ! getent group ${GROUP} > /dev/null; then
    groupadd -f -g ${GID} ${GROUP}
fi

if [ "${USER}" != "root" ]; then
    # macOS UIDs can be less than 1000
    test ${UID} -lt 1000 && flag=-r
    useradd ${flag} --uid ${UID} --gid ${GID} --home ${HOME} -G adm --no-create-home --shell ${SHELL} ${USER} > /dev/null
fi

if [ -n "${SSH_AUTH_SOCK}" ]; then
    chmod 777 "${SSH_AUTH_SOCK}"
fi

cd ${CURRENT_PWD}

# We need to keep the consistent connection socket in a local F/S
export ANSIBLE_HOME=/tmp/ansible_home
mkdir ${ANSIBLE_HOME}
chown ${USER} ${ANSIBLE_HOME}
export ANSIBLE_SSH_CONTROL_PATH_DIR=${ANSIBLE_HOME}/cp
export TTN_ANSIBLE_IN_DOCKER=docker

# Ensure we are logged in if we are running ansible-playbook
if [ "${1}" = "ansible-playbook" ]; then
    ttn-lw-cli --log.level error gateways list 2>&1 > /dev/null
    if [ $? -ne 0 ]; then
	echo "ttn-lw-cli does not appear to be logged in" >&2
	exit 1
    fi
fi

gosu ${USER} "${@}"
