---
#
#	Merge the list of authorized keys into one file
#
- name: Create temporary file
  tempfile:
    state: file
    suffix: temp
  delegate_to: localhost
  register: tempfile

- name: Merge our authorized keys into temporary file
  authorized_key:
    manage_dir: no
    exclusive: no
    user: "{{ ansible_user }}"
    path: "{{ tempfile.path }}"
    key: "{{ item }}"
  loop: "{{ authorized_keys_list | flatten }}"
  when: not ansible_check_mode
  delegate_to: localhost

- name: Read the keys from the temporary file
  set_fact:
    authorized_keys: "{{ lookup('file', tempfile.path).splitlines() | flatten }}"
  when: not ansible_check_mode

- name: Delete temp file
  file:
    path: "{{ tempfile.path }}"
    state: absent
  delegate_to: localhost
  when: not ansible_check_mode
...
