---
#
# Merge the list of authorized keys into one file
#
- name: authorized_keys | Create temporary file
  delegate_to: 127.0.0.1
  ansible.builtin.tempfile:
    state: file
    suffix: temp
  register: conduit_tempfile

- name: authorized_keys | Merge our authorized keys into temporary file
  delegate_to: 127.0.0.1
  ansible.posix.authorized_key:
    manage_dir: false
    exclusive: false
    user: "{{ ansible_user }}"
    path: "{{ conduit_tempfile.path }}"
    key: "{{ item }}"
  loop: "{{ authorized_keys_list | flatten }}"
  when: not ansible_check_mode

- name: authorized_keys | Read the keys from the temporary file
  ansible.builtin.set_fact:
    conduit_authorized_keys: "{{ lookup('file', conduit_tempfile.path).splitlines() | flatten }}"
  when: not ansible_check_mode

- name: authorized_keys | Delete temp file
  delegate_to: 127.0.0.1
  ansible.builtin.file:
    path: "{{ conduit_tempfile.path }}"
    state: absent
  when: not ansible_check_mode

- name: authorized_keys | Fail if we didn't find any keys
  ansible.builtin.fail:
    msg: "No authorized_keys are defined"
  when: not conduit_authorized_keys and not 'ping' in ansible_run_tags
...
