---

- name: Local certs directory
  file:
    dest: /usr/local/share/ca-certificates
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: "Fetch Let's Encrypt root cert"
  local_action: get_url
  args:
    url: "https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem"
    dest: "{{ role_path }}/files"

- name: "Install Let's Encrypt root cert"
  copy:
    dest: /usr/local/share/ca-certificates/lets-encrypt-x3-cross-signed.crt
    src: "{{ item }}"
    mode: "0644"
    owner: root
    group: root
  with_flattened:
    - lets-encrypt-x3-cross-signed.pem
  notify: update-ca-certificates

