---

- name: Get info on /etc/hostname
  stat:
    path: /etc/hostname
  register: s_hostname

- name: Move /etc/hostname to /var/config/ssh if a file
  command: mv /etc/hostname /var/config/
  when: s_hostname.stat.islnk is defined and not s_hostname.stat.islnk

- name: Link /etc/hostname to /var/config/hostname
  file:
    dest: /etc/hostname
    state: link
    src: /var/config/hostname
    force: yes

- name: Set hostname file
  copy:
    dest: /var/config/hostname
    content: "{{ hostname }}"
    mode: "0644"
    owner: root
    group: root
  when: hostname is defined
  notify: Set hostname

- name: Set hostname
  shell: "hostname -F /etc/hostname"
