---

- name: hostname | Get info on /etc/hostname
  ansible.builtin.stat:
    path: /etc/hostname
  register: conduit_s_hostname

- name: hostname | Move /etc/hostname to /var/config/ssh if a file
  ansible.builtin.command: mv /etc/hostname /var/config/
  changed_when: true
  when: conduit_s_hostname.stat.islnk is defined and not conduit_s_hostname.stat.islnk

- name: hostname | Link /etc/hostname to /var/config/hostname
  ansible.builtin.file:
    dest: /etc/hostname
    state: link
    src: /var/config/hostname
    force: true

- name: hostname | Set hostname file
  ansible.builtin.copy:
    dest: /var/config/hostname
    content: "{{ hostname }}\n"
    mode: "0644"
    owner: root
    group: root
  when: hostname is defined

- name: hostname | Set hostname
  ansible.builtin.command: "hostname -F /etc/hostname"
  changed_when: true
