---

#
#	Log rotation
#

- name: Install logrotate
  opkg: 
    state: installed
    pkg: "logrotate"
  when:
    - ansible_local.opkg.logrotate is not defined
  notify: Reload facts

- name: /var/config/logrotate.d
  file:
    name: /var/config/logrotate.d
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Copy in logrotate files
  template:
    src: "{{ item.src }}"
    dest: "/var/config/logrotate.d/{{ item.path|regex_replace('\\.j2$','') }}"
  with_filetree: "../templates/logrotate.d"
  when: item.src|regex_search('\.j2$')

- name: Point /etc/logrotate.d at /var/config/logrotate.d
  file:
    name: /etc/logrotate.d
    state: link
    force: yes
    src: /var/config/logrotate.d

