---

#
# Log rotation
#

- name: logrotate | Install logrotate
  community.general.opkg:
    state: installed
    pkg: "logrotate"
  when:
    - ansible_local.opkg.logrotate is not defined
  notify:
    - Reload facts
    - opkg clean

- name: logrotate | /var/config/logrotate.d
  ansible.builtin.file:
    name: /var/config/logrotate.d
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: logrotate | Copy in logrotate files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/var/config/logrotate.d/{{ item.path|regex_replace('\\.j2$','') }}"
  with_community.general.filetree: "{{ role_path }}/templates/logrotate.d"
  when: item.src|regex_search('\.j2$')

- name: logrotate | Get stat info about /etc/logrotate.d
  ansible.builtin.stat:
    path: /etc/logrotate.d
  register: logrotate_d

- name: logrotate | Remove /etc/logrotate.d
  ansible.builtin.file:
    name: /etc/logrotate.d
    state: absent
  when: logrotate_d.stat.isdir is defined and logrotate_d.stat.isdir == True

- name: logrotate | Point /etc/logrotate.d at /var/config/logrotate.d
  ansible.builtin.file:
    name: /etc/logrotate.d
    state: link
    force: true
    src: /var/config/logrotate.d
  when: logrotate_d.stat.isdir is defined and logrotate_d.stat.isdir == True
