---

- name: monit | Install Monit and dependencies
  community.general.opkg:
    state: installed
    pkg: "{{ item }}"
  when: ansible_local is not defined or ansible_local.opkg is not defined or item|regex_replace('-','_') not in ansible_local.opkg.keys()
  with_items:
    - monit
  notify:
    - Reload facts
    - opkg clean

#
# /var/config/monit/.monit.id
#

- name: monit | Get stat info about /var/config/monit/.monit.id
  ansible.builtin.stat:
    path: /var/config/monit/.monit.id
  register: config_monit_id

- name: monit | Move .monit.id to /var/config/monit if source exists and dest does not
  when: not config_monit_id.stat.exists
  block:
    - name: monit | Find /home/root/.monit.id
      ansible.builtin.stat:
        path: /home/root/.monit.id
      register: monit_id
    - name: monit | Move /home/root/.monit.id
      ansible.builtin.command: mv /home/root/.monit.id /var/config/monit
      when: monit_id.stat.exists and not monit_id.stat.islnk

- name: monit | Link /home/root/.monit.id to /var/config/monit/.monit.id
  ansible.builtin.file:
    path: /home/root/.monit.id
    src: /var/config/monit/.monit.id
    state: link
    force: true
    follow: false

#
# Event Queue
#

- name: monit | Create monit event queue
  ansible.builtin.file:
    name: /var/monit
    state: directory
    mode: "0700"
    owner: root
    group: root
  when: monit_eventqueue is defined
  notify:
    - Restart monit

#
# Test scripts
#

- name: monit | Install monit test scripts
  ansible.builtin.copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: /usr/local/lib/{{ item }}
    mode: "755"
    owner: root
    group: root
  loop:
    - check_pktfwdlog
    - check_basiclog
    - check_system_md5

- name: monit | Install config files
  ansible.builtin.copy:
    src: "{{ role_path }}/files/{{ item | basename }}"
    dest: "{{ item }}"
    mode: "644"
    owner: root
    group: root
  loop:
    - /var/config/system.md5sum.exclude

- name: monit | /var/config/monit/monitrc
  ansible.builtin.template:
    src: monitrc.j2
    dest: /var/config/monit/monitrc
    mode: "700"
    owner: root
    group: root
  notify:
    - Restart monit

- name: monit | Point /etc/monitrc at /var/config/monit/monitrc
  ansible.builtin.file:
    name: /etc/monitrc
    state: link
    force: true
    src: /var/config/monit/monitrc
  notify:
    - Reload facts
    - Restart monit

- name: monit | Enable monit
  ansible.builtin.lineinfile:
    dest: /etc/default/monit
    regexp: "^ENABLED="
    line: 'ENABLED="yes"'
    state: present
  notify:
    - Restart monit
