---

- name: networking | Check that wlan0 exists if we are configuring it as only interface
  ansible.builtin.command: ifconfig wlan0
  changed_when: true
  when:
    - eth0_type is not defined or eth0_type == 'manual'
    - wlan0_type is defined

- name: networking | Check if we need WiFi firmware
  ansible.builtin.import_tasks: wifi_firmware.yml
  when: wlan0_type is defined

- name: networking | Static /etc/resolv.conf
  ansible.builtin.template:
    src: resolv.conf-static.j2
    dest: "{{ resolv_conf_static }}"
    mode: "0644"
    owner: root
    group: root
  when:
    - ( eth0_type is defined and eth0_type == 'static' ) or ( wlan0_type is defined and wlan0_type == 'static' )

- name: networking | Set up dhcp /etc/resolv.conf
  ansible.builtin.file:
    name: /etc/resolv.conf
    state: link
    force: true
    src: /var/run/resolv.conf
  when:
    - eth0_type is not defined or eth0_type != 'static'
    - wlan0_type is not defined or wlan0_type != 'static'

- name: networking | Delete static /etc/resolv.conf if not used
  ansible.builtin.file:
    name: "{{ resolv_conf_static }}"
    state: absent
  when:
    - eth0_type is not defined or eth0_type != 'static'
    - wlan0_type is not defined or wlan0_type != 'static'

- name: networking | Set up /var/config/network/interfaces
  ansible.builtin.template:
    src: interfaces.j2
    dest: /var/config/network/interfaces
    mode: "0644"
    owner: root
    group: root
  notify: interface reboot
  when:
    - eth0_type is defined or wlan0_type is defined

- name: networking | Set up {{ wpa_conf }}
  ansible.builtin.template:
    src: wpa_supplicant.conf.j2
    dest: "{{ wpa_conf }}"
    mode: "0600"
    owner: root
    group: root
  when:
    - wpa_conf is defined
    - wireless_keys is defined

- name: networking | Delete {{ wpa_conf }} if no wireless keys
  ansible.builtin.file:
    name: "{{ wpa_conf }}"
    state: absent
  when:
    - wireless_keys is not defined

- name: networking | Install support scripts
  ansible.builtin.copy:
    dest: "/var/config/{{ item }}"
    src: "{{ item }}"
    mode: "0755"
    owner: root
    group: root
  with_items:
    - udhcpc_restart
    - ifup_restart

- name: networking | Link /etc/udhcpc.d/60restart
  ansible.builtin.file:
    dest: /etc/udhcpc.d/60restart
    src: /var/config/udhcpc_restart
    state: link
    force: true

- name: networking | Link /etc/network/if-up.d/restart
  ansible.builtin.file:
    dest: /etc/network/if-up.d/restart
    src: /var/config/ifup_restart
    state: link
    force: true

#
# Monit
#
- name: networking | /var/config/monit/monit.d/networking.monit
  ansible.builtin.template:
    src: networking.monit.j2
    dest: /var/config/monit/monit.d/networking.monit
    mode: "700"
    owner: root
    group: root
  notify:
    - Restart monit
