---

- name: Check that wlan0 exists if we are configuring it as only interface
  shell: ifconfig wlan0
  when:
    - eth0_type is not defined or eth0_type == 'manual'
    - wlan0_type is defined

- name: Check if we need WiFi firmware
  import_tasks: wifi_firmware.yml
  when: wlan0_type is defined

- name: Static /etc/resolv.conf
  template:
    src: resolv.conf-static.j2
    dest: "{{ resolv_conf_static }}"
    mode: "0644"
    owner: root
    group: root
  when:
    - ( eth0_type is defined and eth0_type == 'static' ) or ( wlan0_type is defined and wlan0_type == 'static' )

- name: Set up dhcp /etc/resolv.conf
  file:
    name: /etc/resolv.conf
    state: link
    force: yes
    src: /var/run/resolv.conf
  when:
    - eth0_type is not defined or eth0_type != 'static'
    - wlan0_type is not defined or wlan0_type != 'static'

- name: Delete static /etc/resolv.conf if not used
  file:
    name: "{{ resolv_conf_static }}"
    state: absent
  when:
    - eth0_type is not defined or eth0_type != 'static'
    - wlan0_type is not defined or wlan0_type != 'static'

- name: Set up /var/config/network/interfaces
  template:
    src: interfaces.j2
    dest: /var/config/network/interfaces
    mode: "0644"
    owner: root
    group: root
  notify: interface reboot
  when:
    - eth0_type is defined or wlan0_type is defined

- name: Set up {{ wpa_conf }}
  template:
    src: wpa_supplicant.conf.j2
    dest: "{{ wpa_conf }}"
    mode: "0600"
    owner: root
    group: root
  when:
    - wpa_conf is defined
    - wireless_keys is defined

- name: Delete {{ wpa_conf }} if no wireless keys
  file:
    name: "{{ wpa_conf }}"
    state: absent
  when:
    - wireless_keys is not defined

- name: Install support scripts
  copy:
    dest: "/var/config/{{ item }}"
    src: "{{ item }}"
    mode: "0755"
    owner: root
    group: root
  with_items:
    - udhcpc_restart
    - ifup_restart

- name: Link /etc/udhcpc.d/60restart
  file:
    dest: /etc/udhcpc.d/60restart
    src: /var/config/udhcpc_restart
    state: link
    force: yes

- name: Link /etc/network/if-up.d/restart
  file:
    dest: /etc/network/if-up.d/restart
    src: /var/config/ifup_restart
    state: link
    force: yes
