---

- name: preserve | Figure out if we need to ignore certificates on older versions
  ansible.builtin.set_fact:
    validate_certs: "{{ ansible_local.mlinux.version is version('3.3.24', '>') }}"

- name: preserve | Fetch preserve script
  ansible.builtin.get_url:
    url: "{{ mlinux_ttni_preserve_root[ansible_distribution_major_version] }}/preserve_config"
    validate_certs: "{{ validate_certs }}"
    dest: /etc/init.d/preserve_config
    mode: "0755"
    owner: root
    group: root

- name: preserve | Enable Preserve service
  ansible.builtin.command: update-rc.d preserve_config start 39 0 6 .
  changed_when: true

- name: preserve | Save a copy of the restore script
  ansible.builtin.get_url:
    url: "{{ mlinux_ttni_preserve_root[ansible_distribution_major_version] }}/restore_config"
    validate_certs: "{{ validate_certs }}"
    dest: /var/config/restore_config
    mode: "0755"
    owner: root
    group: root

- name: preserve | Create restore dir
  ansible.builtin.file:
    dest: /var/config/restore.d
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: preserve | Install restore scripts
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/var/config/restore.d/{{ item }}"
    mode: "0755"
    owner: root
    group: root
  with_items:
    - 05restore
    - 15restore

- name: preserve | Install restore initscript
  ansible.builtin.template:
    src: restore.init.j2
    dest: "/var/config/init.d/restore.init"
    mode: "0755"
    owner: root
    group: root

- name: preserve | Mark restore as completed
  ansible.builtin.file:
    name: /var/lib/restore.done
    state: touch
    mode: "0644"
    owner: root
    group: root
