---    
- name: Create restore dir
  file:
    dest: /var/config/restore.d
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Install restore scripts
  template:
    src: "{{ item }}.j2"
    dest: "/var/config/restore.d/{{ item }}"
    mode: "0755"
    owner: root
    group: root
  with_items:
    - 05restore
    - 15restore

- name: Install restore initscript
  template:
    src: restore.init.j2
    dest: "/var/config/restore.init"
    mode: "0755"
    owner: root
    group: root

- name: Mark restore as completed
  file:
    name: /var/lib/restore.done
    state: touch
    mode: "0644"
    owner: root
    group: root
