---

- name: Get info on /etc/ssh/sshd_config
  stat:
    path: /etc/ssh/sshd_config
  register: sshd_config

- name: Move /etc/ssh/sshd_config to /var/config/ssh if a file
  command: mv /etc/ssh/sshd_config /var/config/ssh
  when: sshd_config.stat.islnk is defined and not sshd_config.stat.islnk
    
- name: Link /etc/ssh/sshd_config to /var/config/ssh/sshd_config
  file:
    dest: /etc/ssh/sshd_config
    state: link
    src: /var/config/ssh/sshd_config
    force: yes

- name: Disallow password authentication
  lineinfile: dest=/var/config/ssh/sshd_config
    regexp="^#?PasswordAuthentication\s"
    line="PasswordAuthentication no"
    state=present
  notify: Restart ssh

- name: Disallow root SSH access
  lineinfile: dest=/var/config/ssh/sshd_config
    regexp="^#?PermitRootLogin\s"
    line="PermitRootLogin without-password"
    state=present
  notify: Restart ssh

