---

- name: sshd | Get info on /etc/ssh/sshd_config
  ansible.builtin.stat:
    path: /etc/ssh/sshd_config
  register: conduit_sshd_config

- name: sshd | Move /etc/ssh/sshd_config to /var/config/ssh if a file
  ansible.builtin.command: mv /etc/ssh/sshd_config /var/config/ssh
  changed_when: true
  when: conduit_sshd_config.stat.islnk is defined and not conduit_sshd_config.stat.islnk

- name: sshd | Link /etc/ssh/sshd_config to /var/config/ssh/sshd_config
  ansible.builtin.file:
    dest: /etc/ssh/sshd_config
    state: link
    src: /var/config/ssh/sshd_config
    force: true

- name: sshd | Disallow password authentication
  ansible.builtin.lineinfile:
    dest: /var/config/ssh/sshd_config
    regexp: '^#?PasswordAuthentication\s'
    line: "PasswordAuthentication no"
    state: present
  notify:
    - Restart ssh
    - Update system checksum file

- name: sshd | Disallow root SSH access
  ansible.builtin.lineinfile:
    dest: /var/config/ssh/sshd_config
    regexp: '^#?PermitRootLogin\s'
    line: "PermitRootLogin without-password"
    state: present
  notify:
    - Restart ssh
    - Update system checksum file
