---

#
# Install all variants of packet forwarder
#

# Install dependencies
#
- name: ttn_packet_forwarder | Install depedencies for packet forwarder
  community.general.opkg:
    state: installed
    pkg: "{{ item }}"
  when: (ansible_local is not defined) or (ansible_local.opkg is not defined) or (item not in ansible_local.opkg.keys())
  with_items:
    - libmpsse
  notify:
    - Reload facts
    - opkg clean

#
# Make sure we have package for correct version
#
- name: ttn_packet_forwarder | Get info on local copy of packet-forwarder package
  delegate_to: 127.0.0.1
  ansible.builtin.stat:
    path: "{{ role_path }}/files/{{ forwarder_package_full }}"
  register: forwarder_package_stat

- name: ttn_packet_forwarder | Download requested version of packet-forwarder
  delegate_to: 127.0.0.1
  ansible.builtin.get_url:
    url: "{{ forwarder_url }}"
    dest: "{{ role_path }}/files"
  when:
    - not forwarder_package_stat.stat.exists

- name: ttn_packet_forwarder | Find old .ipk files
  ansible.builtin.find:
    paths:
      /var/config
    patterns:
      - "*-packet-forwarder_*.ipk"
  register: old_ipk
  when:
    - forwarder_installed != forwarder_package_version

- name: ttn_packet_forwarder | Delete old .ipk files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ old_ipk.files }}"
  when:
    - old_ipk.files is defined

- name: ttn_packet_forwarder | Copy over packet-forwarder
  ansible.builtin.copy:
    src: "{{ forwarder_package_full }}"
    dest: "/var/config/{{ forwarder_package_full }}"
  when:
    - forwarder_installed != forwarder_package_version

- name: ttn_packet_forwarder | Unmonitor packet forwarder if changes are being made
  ansible.builtin.command: "monit unmonitor check_pktfwdlog"
  notify: monit monitor check_pktfwdlog
  ignore_errors: true
  changed_when: true
  when:
    - forwarder_installed != forwarder_package_version

- name: ttn_packet_forwarder | Stop packet-forwarder
  ansible.builtin.service:
    name: ttn-pkt-forwarder
    state: stopped
  when: forwarder_installed != forwarder_package_version
  ignore_errors: true

- name: ttn_packet_forwarder | Remove all existing packet-forwarder packages
  ansible.builtin.command: "opkg remove poly-packet-forwarder mp-packet-forwarder ttn-packet-forwarder"
  changed_when: true
  when:
    - forwarder_installed != forwarder_package_version
  notify: Reload facts

- name: ttn_packet_forwarder | Install {{ forwarder_package_full }}
  ansible.builtin.command: "opkg install /var/config/{{ forwarder_package_full }}"
  changed_when: true
  when: forwarder_installed != forwarder_package_version
  notify:
    - restart ttn-pkt-forwarder
    - Reload facts

- name: ttn_packet_forwarder | Install /var/config/init.d/ttn-pkt-forwarder
  ansible.builtin.template:
    src: ttn-pkt-forwarder.j2
    dest: /var/config/init.d/ttn-pkt-forwarder
    mode: "0755"
    owner: root
    group: root
  notify:
    - restart ttn-pkt-forwarder

- name: ttn_packet_forwarder | Link /etc/init.d/ttn-pkt-forwarder to /var/config/init.d/ttn-pkt-forwarder
  ansible.builtin.file:
    dest: /etc/init.d/ttn-pkt-forwarder
    state: link
    src: /var/config/init.d/ttn-pkt-forwarder
    follow: false
    force: true
  notify:
    - update rc
    - restart ttn-pkt-forwarder

- name: ttn_packet_forwarder | Install /etc/default/ttn-pkt-forwarder
  ansible.builtin.copy:
    src: "{{ role_path }}/files/default.enabled"
    dest: /etc/default/ttn-pkt-forwarder
    mode: "0755"
    owner: root
    group: root
  notify:
    - restart ttn-pkt-forwarder

- name: ttn_packet_forwarder | Stop the LoRA Basic Station
  ansible.builtin.service:
    name: lora-basic-station
    state: stopped
  ignore_errors: true

- name: ttn_packet_forwarder | Disable LoRA Basic Station
  ansible.builtin.lineinfile:
    dest: /etc/default/lora-basic-station
    regexp: "^ENABLED="
    line: 'ENABLED="no"'
    state: present
  ignore_errors: true

#
# Install the TTN config files
#
- name: ttn_packet_forwarder | Local packet forwarder configuration file
  ansible.builtin.template:
    src: local_conf.json.j2
    dest: /var/config/lora/local_conf.json
    mode: "0644"
    owner: root
    group: root
  notify: restart ttn-pkt-forwarder

- name: ttn_packet_forwarder | Packet Forwarder configuration (before 3.0.25)
  when: forwarder_variant != "mp" or forwarder_version is version('3.0.25', '<')
  block:
    - name: ttn_packet_forwarder | Install node.js
      community.general.opkg:
        state: present
        pkg: "{{ item }}"
      when: (ansible_local is not defined) or (ansible_local.opkg is not defined) or (item not in ansible_local.opkg.keys())
      loop:
        - nodejs
      notify:
        - Reload facts
        - opkg clean
    - name: ttn_packet_forwarder | ttn_global_conf.json.j2
      ansible.builtin.template:
        src: global_conf.json.j2
        dest: /var/config/lora/ttn_global_conf.json
        mode: "0644"
        owner: root
        group: root
    - name: ttn_packet_forwarder | merge.js
      ansible.builtin.command: node /opt/lora/merge.js /var/config/lora/ttn_global_conf.json /var/config/lora/multitech_overrides.json /var/config/lora/global_conf.json
      changed_when: true
      notify: restart ttn-pkt-forwarder
    - name: ttn_packet_forwarder | global_conf.json.j2
      ansible.builtin.template:
        src: global_conf.json.j2
        dest: /var/config/lora/global_conf.json
        mode: "0644"
        owner: root
        group: root

- name: ttn_packet_forwarder | Packet Forwarder configuration (3.0.25 and later)
  when: forwarder_variant == "mp" and forwarder_version is version('3.0.25', '>=')
  block:
    - name: ttn_packet_forwarder | Remove node.js
      community.general.opkg:
        state: absent
        pkg: "{{ item }}"
      when: (ansible_local is not defined) or (ansible_local.opkg is not defined) or (item in ansible_local.opkg.keys())
      loop:
        - nodejs
      notify:
        - Reload facts
        - opkg clean
    - name: ttn_packet_forwarder | global_conf.json.j2
      ansible.builtin.template:
        src: global_conf.json.j2
        dest: /var/config/lora/global_conf.json
        mode: "0644"
        owner: root
        group: root
      notify: restart ttn-pkt-forwarder
    - name: ttn_packet_forwarder | Remove ttn_global_conf.json
      ansible.builtin.file:
        dest: /var/config/lora/ttn_global_conf.json
        state: absent

- name: ttn_packet_forwarder | Remove some files
  ansible.builtin.file:
    name: "{{ item }}"
    state: absent
  loop:
    - /etc/init.d/lora-basic-station
    - /var/config/init.d/lora-basic-station
    - /var/config/lora/config.yml
    - /var/config/lora/local_conf.json-opkg
    - /var/config/lora/samples
    - /var/config/lora/station.conf
    - /var/config/lora/tc.*
    - /var/log/basic-station.log*
...
