---

- name: ttn_basic_station Download requested version of packet-forwarder
  local_action: get_url
  args:
    url: "{{ forwarder_url }}"
    dest: "{{ role_path }}/files"
  when:
    - forwarder_package_stat.stat.exists == false



...
