---

# XXX - Should we just fetch the package ourselves?

# XXX - TODO - Switch version and test this code

- name: ttn_basic_station | Stop lora-basic if we are updating it
  ansible.builtin.service: # noqa: ignore-errors
    name: lora-basic-station
    state: stopped
  ignore_errors: true
  when:
    - forwader_version is defined
    - ansible_local.opkg.lora_basic_station is defined and ansible_local.opkg.lora_basic_station != forwarder_version

- name: ttn_basic_station | Uninstall old version of lora_basic_station
  community.general.opkg:
    name: lora_basic_station
    state: absent
    force: remove
  notify:
    - Restart lora-basic-station
  when:
    - forwader_version is defined
    - ansible_local.opkg.lora_basic_station is not defined or ansible_local.opkg.lora_basic_station != forwarder_version

- name: ttn_basic_station | Install the desired version of lora_basic_station
  community.general.opkg:
    name: "lora_basic_station=={{ forwarder_version }}"
    state: present
  notify:
    - Restart lora-basic-station
  when:
    - forwader_version is defined
    - ansible_local.opkg.lora_basic_station is not defined or ansible_local.opkg.lora_basic_station != forwarder_version

# We have a program below because MT posted the data in an invalid format
- name: ttn_basic_station | Fetch and update station.conf
  block:
    - name: ttn_basic_station | Fact gps_arg
      ansible.builtin.set_fact:
        conduit_gps_arg: "--gps /dev/{{ gps_device }}"
      when: have_gps and use_gps
    - name: ttn_basic_station | Fact gps_arg
      ansible.builtin.set_fact:
        conduit_gps_arg: ""
      when: not (have_gps and use_gps)
    - name: ttn_basic_station | Fact mt_station_conf
      delegate_to: 127.0.0.1
      ansible.builtin.command: |
        bin/mt_station_conf --url {{ basic_station_conf_url[conduit_type] }}
         --routerid {{ ansible_local.lora.eui }}
         --log-file {{ basic_log_file }}
         --log-level {{ basic_log_level }}
         --log-size {{ forwarder_logrotate_size }}
         --log-rotate {{ forwarder_logrotate_count }}
         {{ conduit_gps_arg }}
      changed_when: true
      register: conduit_station_conf_raw
    - name: ttn_basic_station | Fact station_conf
      ansible.builtin.set_fact:
        conduit_station_conf: "{{ conduit_station_conf_raw.stdout | from_json }}"

- name: ttn_basic_station | Install /var/config/lora/station.conf
  ansible.builtin.template:
    src: station.conf.j2
    dest: /var/config/lora/station.conf
    mode: "0644"
    owner: root
    group: root
  notify:
    - Restart lora-basic-station

- name: ttn_basic_station | Download certificate
  delegate_to: 127.0.0.1
  ansible.builtin.get_url:
    url: "{{ basic_cert_url }}"
    dest: "{{ role_path }}/files"
    mode: '0644'

- name: ttn_basic_station | Install certificate /var/config/lora/tc.trust
  ansible.builtin.copy:
    src: "{{ role_path }}/files/{{ basic_cert_url | basename }}"
    dest: "/var/config/lora/tc.trust"
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart lora-basic-station

- name: ttn_basic_station | Install gateway key /var/config/lora/tc.key
  ansible.builtin.template:
    src: tc.key.j2
    dest: /var/config/lora/tc.key
    newline_sequence: '\r\n'
    mode: "0600"
    owner: root
    group: root
  notify:
    - Restart lora-basic-station

- name: ttn_basic_station | Install uri file /var/config/lora/tc.uri
  ansible.builtin.template:
    src: tc.uri.j2
    dest: /var/config/lora/tc.uri
    newline_sequence: '\r\n'
    mode: "0644"
    owner: root
    group: root
  notify:
    - Restart lora-basic-station

#
# Cleanup
#

- name: ttn_basic_station | Install /var/config/lora-basic-station
  ansible.builtin.template:
    src: lora-basic-station.j2
    dest: /var/config/init.d/lora-basic-station
    mode: "0755"
    owner: root
    group: root
  notify:
    - Restart lora-basic-station

- name: ttn_basic_station | /etc/init.d/lora-basic-station to /var/config/lora/lora-basic-station
  ansible.builtin.file:
    dest: /etc/init.d/lora-basic-station
    state: link
    src: /var/config/init.d/lora-basic-station
    follow: false
    force: true
  notify:
    - Update rc
    - Restart lora-basic-station

- name: ttn_basic_station | Enable basic station
  ansible.builtin.lineinfile:
    dest: /etc/default/lora-basic-station
    regexp: "^ENABLED="
    line: 'ENABLED="yes"'
    state: present
  notify:
    - Restart lora-basic-station

- name: ttn_basic_station | Stop the packet fowarder
  ansible.builtin.service: # noqa: ignore-errors
    name: ttn-pkt-forwarder
    state: stopped
  ignore_errors: true

- name: ttn_basic_station |  Disable ttn-pkt-forwarder
  ansible.builtin.lineinfile: # noqa: ignore-errors
    dest: /etc/default/ttn-pkt-forwarder
    regexp: "^ENABLED="
    line: 'ENABLED="no"'
    state: present
  ignore_errors: true

- name: ttn_basic_station | Remove some files
  ansible.builtin.file:
    name: "{{ item }}"
    state: absent
  loop:
    - /etc/init.d/ttn-pkt-forwarder
    - /var/config/*.ipk
    - /var/config/init.d/ttn-pkg-forwarder
    - /var/config/lora/global_conf.json
    - /var/config/lora/local_conf.json
    - /var/config/lora/samples
    - /var/log/ttn-pkg-fwd.log*
...
