---

# XXX - Should we just fetch the package ourselves?

# XXX - TODO - Switch version and test this code

- name: ttn_basic_station Stop lora-basic if we are updating it
  service:
    name: lora-basic-station
    state: stopped
  ignore_errors: true
  when:
    - forwader_version is defined
    - ansible_local.opkg.lora_basic_station is defined and ansible_local.opkg.lora_basic_station != forwarder_version

- name: ttn_basic_station Uninstall old version of lora_basic_station
  opkg:
    name: lora_basic_station
    state: absent
    force: remove
  notify:
    - Restart lora-basic-station
  when:
    - forwader_version is defined
    - ansible_local.opkg.lora_basic_station is not defined or ansible_local.opkg.lora_basic_station != forwarder_version

- name: ttn_basic_station Install the desired version of lora_basic_station  
  opkg:
    name: "lora_basic_station=={{ forwarder_version }}"
    state: present
  notify:
    - Restart lora-basic-station
  when:
    - forwader_version is defined
    - ansible_local.opkg.lora_basic_station is not defined or ansible_local.opkg.lora_basic_station != forwarder_version

- name: ttn_basic_station Download certificate
  local_action: get_url
  args:
    url: "{{ basic_cert_url }}"
    dest: "{{ role_path }}/files"

- name: ttn_basic_station Install certificate /var/config/lora/tc.trust
  copy:
    src: "{{ role_path }}/files/{{ basic_cert_url | basename }}"
    dest: "/var/config/lora/tc.trust"
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart lora-basic-station

- name: ttn_basic_station Install gateway key /var/config/lora/tc.key
  template:
    src: tc.key.j2
    dest: /var/config/lora/tc.key
    newline_sequence: '\r\n'
    mode: "0600"
    owner: root
    group: root
  notify:
    - Restart lora-basic-station

- name: ttn_basic_station Install uri file /var/config/lora/tc.uri
  template:
    src: tc.uri.j2
    dest: /var/config/lora/tc.uri
    newline_sequence: '\r\n'
    mode: "0644"
    owner: root
    group: root
  notify:
    - Restart lora-basic-station

- name: ttn_basic_station Fetch and update station.conf
  ansible.builtin.uri:
    url: "{{ basic_station_conf_url }}"
    return_content: true
  register: station_conf_raw
  delegate_to: localhost

- set_fact:
    station_conf: "{{ station_conf_raw.json | combine(basic_station_conf_update) }}"

- name: ttn_basic_station Install /var/config/lora/station.conf
  template:
    src: station.conf.j2
    dest: /var/config/lora/station.conf
    mode: "0644"
    owner: root
    group: root
  notify:
    - Restart lora-basic-station

- name: ttn_basic_station Enable basic station
  lineinfile: dest=/etc/default/lora-basic-station
    regexp="^ENABLED="
    line='ENABLED="yes"'
    state=present
  notify:
    - Restart lora-basic-station

- name: ttn_basic_station Stop the packet fowarder
  service:
    name: ttn-pkt-forwarder
    state: stopped
  ignore_errors: true

- name: ttn_basic_station Remove some files
  file:
    name: "{{ item }}"
    state: absent
  loop:
    - /var/config/lora/global_conf.json
    - /var/config/lora/local_conf.json
    - /var/config/lora/ttn-pkt-forwarder
    - /etc/init.d/ttn-pkt-forwarder
...
