---

#
#	Register gateway with TTNv2
#

- name: ttnv2 check if logged into TTN and refresh key
  local_action:
    module: shell
    args: "bin/ttnctl user status"
  run_once: true

- name: ttnv2 register gateway and delete old name if necessary
  local_action:
    module: shell
    args:
      "bin/register
        --json
        --id {{ lora_hostname }} 
      	--region {{ region }}
        --latitude {{ latitude }}
        --longitude {{ longitude }}
        --router {{ router }}
        --description {{ description | quote }}
        --brand {{ gateway_brand | quote }}
        --model {{ gateway_model | quote }}
        --antenna-type {{ antenna_type | quote }}
        --antenna-model {{ antenna_model | quote }}
        --old_id {{ lora_hostname_delete }}
        --collaborators '{{ gateway_collaborators | to_json }}'"
  register: register_output
  notify: register gateway

- name: ttnv2 Set the gateway_info fact
  set_fact:
    gateway_info: "{{ register_output.stdout }}"
  when: forwarder_variant == 'mp'

- name: ttnv2 Set Some facts
  set_fact:
    gw_key: "{{ gateway_info|json_query('key') }}"
    gw_router: "{{ gateway_info|json_query('info.router.mqtt_address')|urlsplit('hostname') }}"
  when: forwarder_variant == 'mp'

- debug:
    msg: "key {{ gw_key }} router {{ gw_router }}"

- name: ttnv2 Global packet forwarder configuration file
  uri:
    url: "https://raw.githubusercontent.com/TheThingsNetwork/gateway-conf/master/{{ region }}-global_conf.json"
  register: get_config
  ignore_errors: true
  delegate_to: 127.0.0.1

- name: ttnv2 Extract global.conf
  set_fact:
    global_conf: "{{ get_config.json }}"
...
