---
- name: ttnv3_cleanup | Get all link keys
  delegate_to: 127.0.0.1
  ansible.builtin.command: "ttn-lw-cli gateway api-keys list {{ lora_hostname }}"
  changed_when: true
  throttle: 1
  register: conduit_list_keys

- name: ttnv3_cleanup | Delete all link keys that are not in use
  delegate_to: 127.0.0.1
  ansible.builtin.command: "ttn-lw-cli gateway api-keys delete {{ lora_hostname }} {{ item.id }}"
  changed_when: true
  throttle: 1
  loop: "{{ conduit_list_keys.stdout | from_json }}"
  when: item.name == "link" and item.id != conduit_gw_key_id
...
