---
- name: ttnv3_cleanup Get all link keys
  local_action:
    module: shell
    args:
      "ttn-lw-cli gateway api-keys list {{ lora_hostname }}"
  register: list_keys

- name: ttnv3_cleanup Delete all link keys that are not in use
  local_action:
    module: shell
    args: "ttn-lw-cli gateway api-keys delete {{ lora_hostname }} {{item.id }}"
  loop: "{{ list_keys.stdout | from_json }}"
  no_log: true
  when: item.name == "link" and item.id != gw_key_id
...
