---

#
#	Setup users
#

- name: Create non-volatile home dirs
  file:
    dest: /var/config/home
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: "Set up dirs for root"
  import_tasks: user_dirs.yml
  vars:
    target_user: "root"

#
#	Create ttn user
#
- name: "Set up {{ ttn_user }} user"
  user:
    name: "{{ ttn_user }}"
    append: yes
    groups: adm,dialout,disk,plugdev,sudo
    shell: /bin/bash
    password: "*"

- name: Configure mtadm user
  block:
    - import_tasks: user_dirs.yml
    - import_tasks: user_sudo.yml
  vars:
    target_user: ttn

#
#	Configure mtadm user
#

- name: Configure mtadm user
  block:
    - import_tasks: user_dirs.yml
    - import_tasks: user_sudo.yml
    - lineinfile:
        dest: /etc/pam.d/sshd
        regex: ^(auth .*)$
        line: '# \1'
        backrefs: true
  vars:
    target_user: mtadm
  when:
    - mlinux_version is version('4', '>=')
