---

#
# Setup users
#

- name: users | Create non-volatile home dirs
  file:
    dest: /var/config/home
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: users | "Set up dirs for root"
  import_tasks: user_dirs.yml
  vars:
    target_user: "root"

#
# Create ttn user
#
- name: users | "Set up {{ ttn_user }} user"
  user:
    name: "{{ ttn_user }}"
    append: yes
    groups: adm,dialout,disk,plugdev,sudo
    shell: /bin/bash
    password: "*"

- name: users | Configure mtadm user
  block:
    - name: users | ttn dirs
      import_tasks: user_dirs.yml
    - name: users | ttn sudo
      import_tasks: user_sudo.yml
  vars:
    target_user: ttn

#
# Configure mtadm user
#

- name: users | Configure mtadm user
  block:
    - name: users | mtadm dirs
      import_tasks: user_dirs.yml
    - name: users | mtadm sudo
      import_tasks: user_sudo.yml
    - name: users | Disable pam auth functions
      lineinfile:
        dest: /etc/pam.d/sshd
        regex: ^(auth .*)$
        line: '# \1'
        backrefs: true
  vars:
    target_user: mtadm
  when:
    - ansible_local.mlinux.version is version('4', '>=')
