---

#
# Setup user dirs
#

- name: user_dirs | Set facts 1
  ansible.builtin.set_fact:
    ttn_newhomedir: "/var/config/home/{{ target_user }}"

- name: user_dirs | Set facts 2
  ansible.builtin.set_fact:
    ttn_newsshdir: "{{ ttn_newhomedir }}/.ssh"

- name: user_dirs | "Get info about /var/config/home/{{ target_user }}"
  ansible.builtin.stat:
    path: "/var/config/home/{{ target_user }}"
  register: ttn_newhomedir_stat

- name: user_dirs | "Get info about /home/{{ target_user }}/.ssh"
  ansible.builtin.stat:
    path: "/home/{{ target_user }}/.ssh"
  register: ttn_sshdir_stat

- name: user_dirs | "Create {{ target_user }} dirs"
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    mode: "0700"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
  with_items:
    - "{{ ttn_newhomedir }}"
    - "{{ ttn_newsshdir }}"

- name: user_dirs | Copy /home/{{ target_user }}/.ssh content to /var/config/home/{{target_user }}/.ssh
  delegate_to: "{{ inventory_hostname }}"
  ansible.builtin.synchronize:
    archive: true
    src: "{{ ttn_sshdir_stat.stat.path }}/"
    dest: "{{ ttn_newsshdir }}"
  when:
    - ttn_sshdir_stat.stat.exists
    - ttn_sshdir_stat.stat.lnk_target is not defined

- name: user_dirs | Remove existing .ssh dir
  ansible.builtin.file:
    dest: "/home/{{ target_user }}/.ssh"
    state: absent
  when:
    - ttn_sshdir_stat.stat.exists
    - ttn_sshdir_stat.stat.lnk_target is not defined or ttn_sshdir_stat.stat.lnk_target != ttn_newsshdir

- name: user_dirs | Replace /home/{{ target_user }}/.ssh with a symlink to {{ ttn_newsshdir }}
  ansible.builtin.command: "ln -fTs {{ ttn_newsshdir }} /home/{{
  target_user }}/.ssh" # noqa: deprecated-command-syntax
  when:
    - ttn_sshdir_stat.stat.lnk_target is not defined or ttn_sshdir_stat.stat.lnk_target != ttn_newsshdir

- name: user_dirs | "Install {{ target_user }} authorized keys"
  ansible.posix.authorized_key:
    manage_dir: no
    path: "{{ ttn_newsshdir }}/authorized_keys"
    user: "{{ target_user }}"
    key: "{{ authorized_keys | join('\n') }}"
    exclusive: true
