---

#
#	Setup users
#

- name: Create non-volatile home dirs
  file:
    dest: /var/config/home
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Create root non-volatile home dir
  file:
    dest: /var/config/home/root
    state: directory
    mode: "0700"
    owner: root
    group: root

- name: Create root .ssh dir
  file:
    dest: /var/config/home/root/.ssh
    state: directory
    mode: "0700"
    owner: root
    group: root

- name: Get info about ~root/.ssh
  stat:
    path: ~root/.ssh
  register: root_ssh

- name: Copy ~root/.ssh content to /var/config/
  shell: "rsync -av ~root/.ssh /var/config/home/root"
  when: root_ssh.stat.isdir is defined and root_ssh.stat.isdir

- name: Install root authorized keys
  authorized_key:
    manage_dir: no
    path: /var/config/home/root/.ssh/authorized_keys
    user: root
    key: "{{ item }}"
  with_flattened: "{{ authorized_keys }}"

- name: Remove ~root/.ssh if it is a dir
  file:
    dest: ~root/.ssh
    state: absent
  when:
    - root_ssh.stat.isdir is defined and root_ssh.stat.isdir

- name: Create link to /var/config/home/root/.ssh
  file:
    dest: ~root/.ssh
    state: link
    src: /var/config/home/root/.ssh
    force: yes

#
#	Create ttn user
#
- name: "Set up {{ ttn_user }} user"
  user:
    name: "{{ ttn_user }}"
    append: yes
    groups: adm,plugdev,sudo
    shell: /bin/bash
    password: "*"

- name: "Create {{ ttn_user }} non-volatile home dir"
  file:
    dest: "/var/config/home/{{ ttn_user }}"
    state: directory
    mode: "0700"
    owner: "{{ ttn_user }}"
    group: "{{ ttn_user }}"

- name: "Create {{ ttn_user }} .ssh dir"
  file:
    dest: "/var/config/home/{{ ttn_user }}/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ ttn_user }}"
    group: "{{ ttn_user }}"

- name: "Get info about ~{{ ttn_user }}/.ssh"
  stat:
    path: "~{{ ttn_user }}/.ssh"
  register: ttn_ssh

- name: Copy ~{{ ttn_user }}/.ssh content to /var/config/
  shell: "rsync -av ~{{ ttn_user }}/.ssh /var/config/home/{{ ttn_user }}"
  when: ttn_ssh.stat.isdir is defined and ttn_ssh.stat.isdir

- name: "Install {{ ttn_user }} authorized keys"
  authorized_key:
    manage_dir: no
    path: /var/config/home/{{ ttn_user }}/.ssh/authorized_keys
    user: "{{ ttn_user }}"
    key: "{{ item }}"
  with_flattened: "{{ authorized_keys }}"

- name: "Remove ~{{ ttn_user }}/.ssh"
  file:
    dest: "~{{ ttn_user }}/.ssh"
    state: absent
  when:
    - ttn_ssh.stat.isdir is defined and ttn_ssh.stat.isdir

- name: "Create link to /var/config/home/{{ ttn_user }}/.ssh"
  file:
    dest: "~{{ ttn_user }}/.ssh"
    state: link
    src: "/var/config/home/{{ ttn_user }}/.ssh"
    force: yes

- name: "Allow {{ ttn_user }} to sudo without a password"
  copy:
    dest: "/var/config/{{ ttn_user }}.sudo"
    content: "{{ ttn_user }} ALL=(ALL) NOPASSWD: ALL"
    mode: "0644"
    owner: root
    group: root
  when: ansible_local.opkg.sudo is defined

- name: "Create a link to /var/config/{{ ttn_user }}.sudo"
  file:
    dest: "/etc/sudoers.d/{{ ttn_user }}"
    state: link
    src: "/var/config/{{ ttn_user }}.sudo"
    force: yes
  when: ansible_local.opkg.sudo is defined
