---

#
#	Setup users
#

- name: Create non-volatile home dirs
  file:
    dest: /var/config/home
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: "Set up dirs for root"
  import_tasks: user_dirs.yml
  vars:
    target_user: "root"

#
#	Create ttn user
#
- name: "Set up {{ ttn_user }} user"
  user:
    name: "{{ ttn_user }}"
    append: yes
    groups: adm,plugdev,sudo
    shell: /bin/bash
    password: "*"

- name: "Set up dirs for {{ ttn_user }}"
  import_tasks: user_dirs.yml
  vars:
    target_user: "{{ ttn_user }}"

- name: "Allow {{ ttn_user }} to sudo without a password"
  copy:
    dest: "/var/config/{{ ttn_user }}.sudo"
    content: "{{ ttn_user }} ALL=(ALL) NOPASSWD: ALL"
    mode: "0644"
    owner: root
    group: root
  when: ansible_local.opkg.sudo is defined

- name: "Create a link to /var/config/{{ ttn_user }}.sudo"
  file:
    dest: "/etc/sudoers.d/{{ ttn_user }}"
    state: link
    src: "/var/config/{{ ttn_user }}.sudo"
    force: yes
  when: ansible_local.opkg.sudo is defined
