---

#
# Setup user dirs
#

- name: user_dirs | Set facts 1
  ansible.builtin.set_fact:
    conduit_ttn_newhomedir: "/var/config/home/{{ conduit_target_user }}"

- name: user_dirs | Set facts 2
  ansible.builtin.set_fact:
    conduit_ttn_newsshdir: "{{ conduit_ttn_newhomedir }}/.ssh"

- name: user_dirs | "Get info about /home/{{ conduit_target_user }}/.ssh"
  ansible.builtin.stat:
    path: "/home/{{ conduit_target_user }}/.ssh"
  register: conduit_ttn_sshdir_stat

- name: user_dirs | "Create {{ conduit_target_user }} dirs"
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    mode: "0700"
    owner: "{{ conduit_target_user }}"
    group: "{{ conduit_target_user }}"
  with_items:
    - "{{ conduit_ttn_newhomedir }}"
    - "{{ conduit_ttn_newsshdir }}"

- name: user_dirs | Copy /home/{{ conduit_target_user }}/.ssh content to /var/config/home/{{ conduit_target_user }}/.ssh
  delegate_to: "{{ inventory_hostname }}"
  ansible.posix.synchronize:
    archive: true
    src: "{{ conduit_ttn_sshdir_stat.stat.path }}/"
    dest: "{{ conduit_ttn_newsshdir }}"
  when:
    - conduit_ttn_sshdir_stat.stat.exists
    - conduit_ttn_sshdir_stat.stat.lnk_target is not defined

- name: user_dirs | Remove existing .ssh dir
  ansible.builtin.file:
    dest: "/home/{{ conduit_target_user }}/.ssh"
    state: absent
  when:
    - conduit_ttn_sshdir_stat.stat.exists
    - conduit_ttn_sshdir_stat.stat.lnk_target is not defined or conduit_ttn_sshdir_stat.stat.lnk_target != conduit_ttn_newsshdir

- name: user_dirs | Replace /home/{{ conduit_target_user }}/.ssh with a symlink to {{ conduit_ttn_newsshdir }}
  ansible.builtin.command: "ln -fTs {{ conduit_ttn_newsshdir }} /home/{{ conduit_target_user }}/.ssh" # noqa: no-free-form
  changed_when: true
  when:
    - conduit_ttn_sshdir_stat.stat.exists
    - conduit_ttn_sshdir_stat.stat.lnk_target is not defined or conduit_ttn_sshdir_stat.stat.lnk_target != conduit_ttn_newsshdir

- name: user_dirs | "Install {{ conduit_target_user }} authorized keys"
  ansible.posix.authorized_key:
    manage_dir: false
    path: "{{ conduit_ttn_newsshdir }}/authorized_keys"
    user: "{{ conduit_target_user }}"
    key: "{{ conduit_authorized_keys | join('\n') }}"
    exclusive: true
