#
#
#

- name: wifi_firmware | WiFi firmware dirs
  ansible.builtin.file:
    dest: "/lib/firmware/{{ item }}"
    state: directory
    mode: "0755"
    owner: root
    group: root
  with_items:
    - rtlwifi

- name: wifi_firmware |  Check if rtl8192cu firmware is downloaded
  delegate_to: 127.0.0.1
  ansible.builtin.stat:
    path: "{{ role_path }}/files/{{ rtl8192cu_firmware_file }}"
  register: conduit_rtl8192cufw_stat
  when:
    - "'rtl8192cu' in ansible_local.usb.drivers"
    - rtl8192cu_firmware_path not in ansible_local.firmware

- name: wifi_firmware | Download rtl8192cu firmware
  delegate_to: 127.0.0.1
  ansible.builtin.get_url:
    url: "{{ rtl8192cu_firmware_url }}"
    dest: "{{ role_path }}/files"
    mode: '0644'
  when:
    - "'rtl8192cu' in ansible_local.usb.drivers"
    - rtl8192cu_firmware_path not in ansible_local.firmware
    - not conduit_rtl8192cufw_stat.stat.exists

- name: wifi_firmware | Install rtl8192cu firmware
  ansible.builtin.copy:
    src: "{{ role_path }}/files/{{ rtl8192cu_firmware_file }}"
    dest: "/lib/firmware/{{ rtl8192cu_firmware_path }}"
    mode: '0644'
  notify: interface reboot
  when:
    - "'rtl8192cu' in ansible_local.usb.drivers"
    - rtl8192cu_firmware_path not in ansible_local.firmware
